= Development

== Template Development Instructions

* Make a change in a template, e.g. +templates/dolphin-client-javafx-java+
* In the top folder execute `./gradlew installTemplateXYZ` which will install the template into `~/.lazybones/templates/XYZ....zip`
(alternatively call `./gradlew installAllTemplates`)
* In an arbitrary directory execute +lazybones createXYZ <NEW-VERSION-NUMBER> <modulename>+ which will create the folder +<modulename>+ and expand the template into it.
* Test the generated module and repeat the previous steps until you are satisfied with the result

== Publishing
* In the top level folder invoke +./gradlew publishTemplateXYZ+ . Note: the first time a package needs to be created with the bintray Web-GUI in the 'lazybones-templates' repository with a name ending in '-template' (e.g. 'open-dolphin-javafx-java-template').

== Template installation
in root folder:

[source,shell]
----
./gradlew installTemplateDolphinServerJava
----

== Template usage
in an empty folder:

[source,shell]
----
lazybones create dolphin-server-java 0.0.1 ods
----


lb create -Pgroup=org.group -Pversion=0.1.0-SNAPSHOT -PpackageName=org.group open-dolphin 0.0.4 myod && cd myod
lb --logLevel=FINE generate -PmoduleName=server dolphin-server-java


= Usage

=== Complete Java setup

[source]
----
lazybones create -Pdv dolphin-client-javafx-java 0.0.4 client
lazybones create -Pdv dolphin-combined-java 0.0.2 combined
lazybones create -Pdv dolphin-server-java 0.0.4 server
lazybones create -Pdv dolphin-shared-java 0.0.4 shared
----

All as one groovy script:

[source]
.j.groovy
----
"lazybones create -Pdv dolphin-client-javafx-java 0.0.4 client".execute()
"lazybones create -Pdv dolphin-combined-java 0.0.2 combined".execute()
"lazybones create -Pdv dolphin-server-java 0.0.4 server".execute()
"lazybones create -Pdv dolphin-shared-java 0.0.4 shared".execute()
"lazybones create -Pdv dolphin-server-webapp 0.0.4 webapp".execute()
----

=== Complete Groovy setup

[source]
----
lazybones create -Pdv dolphin-client-javafx-groovy 0.0.4 client
lazybones create -Pdv dolphin-combined-groovy 0.0.2 combined
lazybones create -Pdv dolphin-server-groovy 0.0.4 server
lazybones create -Pdv dolphin-shared-groovy 0.0.4 shared
----


All as one groovy script:

[source]
.g.groovy
----
"lazybones create -Pdv dolphin-client-javafx-groovy 0.0.4 client".execute()
"lazybones create -Pdv dolphin-combined-groovy 0.0.2 combined".execute()
"lazybones create -Pdv dolphin-server-groovy 0.0.4 server".execute()
"lazybones create -Pdv dolphin-shared-groovy 0.0.4 shared".execute()
"lazybones create -Pdv dolphin-server-webapp 0.0.4 webapp".execute()
----

=== Testing

==== Java

* call `groovy j.groovy`
...

==== Groovy

* call `groovy g.groovy`
...
