= Development

== Template Development Instructions

* Make a change in a template, e.g. +templates/dolphin-client-javafx-java+
* In the top folder execute +./gradlew installTemplateXYZ+ which will install the template into +~/.lazybones/templates/XYZ....zip+
* In an arbitrary directory execute +lazybones createXYZ 0.0.6 <modulename>+ which will create the folder +<modulename>+ and expand the template into it.
* Test the generated module and repeat the previous steps until you are satisfied with the result

== Publishing
* In the top level folder invoke +./gradlew publishTemplateXYZ+ . Note: the first time a package needs to be created with the bintray Web-GUI in the 'lazybones-templates' repository with a name ending in '-template' (e.g. 'open-dolphin-javafx-java-template').

== Template installation
in root folder:

[source,shell]
----
./gradlew installTemplateDolphinServerJava
----

== Template usage
in an empty folder:

[source,shell]
----
lazybones create dolphin-server-java 0.0.1 ods
----


lb create -Pgroup=org.group -Pversion=0.1.0-SNAPSHOT -PpackageName=org.group open-dolphin 0.0.4 myod && cd myod
lb --logLevel=FINE generate -PmoduleName=server dolphin-server-java


= Usage

== Create Project Folder

* lazybones create open-dolphin 0.0.4 hello_dolphin
* cd hello_dolphin
* ./setup_for_java.sh or ./setup_for_groovy.sh

== Run the application:
./gradlew :combined:run

== Appendix

=== Popular module combinations

[source]
.Complete Java setup
----
lazybones create -Pdv dolphin-client-javafx-java 0.0.3 client
lazybones create -Pdv dolphin-combined-java 0.0.2 combined
lazybones create -Pdv dolphin-server-java 0.0.3 server
lazybones create -Pdv dolphin-shared-java 0.0.3 shared
----

[source]
.g.groovy
----
"lazybones create -Pdv dolphin-client-javafx-java 0.0.3 client".execute()
"lazybones create -Pdv dolphin-combined-java 0.0.2 combined".execute()
"lazybones create -Pdv dolphin-server-java 0.0.3 server".execute()
"lazybones create -Pdv dolphin-shared-java 0.0.3 shared".execute()
"lazybones create -Pdv dolphin-server-webapp 0.0.3 webapp".execute()
----

