= OpenDolphin Lazybones templates

These project templates make it very easy to create new OpenDolphin based applications.

== Installation of Lazybones using gvm (Linux, OS/X)

Install gvm:

-----------
$ curl -s get.gvmtool.net | bash
-----------

Install lazybones:

-----------
$ gvm install lazybones
-----------

Add the entry +"svene/lazybones"+ to your +$HOME/.lazybones/config.groovy+ file:

-----------
bintrayRepositories = [
    "opendolphin/lazybones-templates",
    ...
-----------


== Installation of Lazybones without gvm
Grab the distribution from https://bintray.com/pkg/show/general/pledbrook/lazybones-templates/lazybones[Bintray], unpack it to a local directory, and then add its +bin+ directory to your PATH environment variable.

== Usage

=== OpenDolphin Template
In an arbitrary directory execute +lazybones create opendolphin +first_opendolphin+ which will create the folder +first_opendolphin+ and expand the template into it.
The folder contains a +build.gradle+ file.

You can run the application in two modes, the 'develop/test/debug' mode and the 'remote' mode.

To run it in develop mode invoke:

-----
	./gradlew :combined:run
-----

which should show a small window with a button on it. If you click it you should see some messages
on the terminal illustrating the commands which are sent from client to server and vice versa.


To run int in groovy and development mode invoke:

-----
	./gradlew runWithGroovy
-----

To run it in remote mode invoke:

-----
	./gradlew jettyRun
-----

and in a second terminal

-----
	./gradlew :client:run
-----

Note that the client and the server communication messages now appear in the client respectively server terminal.

To continue have a look at the Open Dolphin tutorial of https://github.com/canoo/DolphinJumpStart[DolphinJumpStart]

== Development

* Make a change in a template, e.g. +templates/opendolphin+
* In top folder execute +./gradlew installTemplateOpenDolphin+ which will install the +opendolphin+ template into +~/.lazybones/templates/opendolphin-0.0.1.zip+
* In an arbitrary directory execute +lazybones create opendolphin 0.0.1 javaee7+ which will create the folder +opendolphin+ and expand the template into it.
* Repeat the previous steps until you are satisfied with the result

== Publishing
* In the top level folder invoke +./gradlew publishTemplateOpenDolphin+ . Note: the first time a package needs to be created with the bintray Web-GUI in the 'lazybones-templates' repository with a name ending in '-template' (for this example 'open-dolphin-template').


